# flake8: noqa

news = """ 
        """

language_data = {
    "english": {
        "description": """
        """,
        "tutorial": """
        """,
        "tab_translate": "Video translation",
        "video_source": "Choose Video Source",
        "link_label": "Media link.",
        "link_info": "Example: www.youtube.com/watch?v=g_9rPvbENUw",
        "link_ph": "URL goes here...",
        "dir_label": "Video Path.",
        "dir_info": "Example: /usr/home/my_video.mp4",
        "dir_ph": "Path goes here...",
        "sl_label": "Source language",
        "sl_info": "This is the original language of the video",
        "tat_label": "Translate audio to",
        "tat_info": "Select the target language and also make sure to choose the corresponding TTS for that language.",
        "num_speakers": "Select how many people are speaking in the video.",
        "min_sk": "Min speakers",
        "max_sk": "Max speakers",
        "tts_select": "Select the voice you want for each speaker.",
        "sk1": "TTS Speaker 1",
        "sk2": "TTS Speaker 2",
        "sk3": "TTS Speaker 3",
        "sk4": "TTS Speaker 4",
        "sk5": "TTS Speaker 5",
        "sk6": "TTS Speaker 6",
        "sk7": "TTS Speaker 7",
        "sk8": "TTS Speaker 8",
        "sk9": "TTS Speaker 9",
        "sk10": "TTS Speaker 10",
        "sk11": "TTS Speaker 11",
        "sk12": "TTS Speaker 12",
        "vc_title": "Voice Imitation in Different Languages",
        "vc_subtitle": """
        ### Replicate a person's voice across various languages.
        While effective with most voices when used appropriately, it may not achieve perfection in every case.
        Voice Imitation solely replicates the reference speaker's tone, excluding accent and emotion, which are governed by the base speaker TTS model and not replicated by the converter.
        This will take audio samples from the main audio for each speaker and process them.
        """,
        "vc_active_label": "Active Voice Imitation",
        "vc_active_info": "Active Voice Imitation: Replicates the original speaker's tone",
        "vc_method_label": "Method",
        "vc_method_info": "Select a method for Voice Imitation process",
        "vc_segments_label": "Max samples",
        "vc_segments_info": "Max samples: Is the number of audio samples that will be generated for the process, more is better but it can add noise",
        "vc_dereverb_label": "Dereverb",
        "vc_dereverb_info": "Dereverb: Applies vocal dereverb to the audio samples.",
        "vc_remove_label": "Remove previous samples",
        "vc_remove_info": "Remove previous samples: Remove the previous samples generated, so new ones need to be created.",
        "xtts_title": "Create a TTS based on an audio",
        "xtts_subtitle": "Upload an audio file of maximum 10 seconds with a voice. Using XTTS, a new TTS will be created with a voice similar to the provided audio file.",
        "xtts_file_label": "Upload a short audio with the voice",
        "xtts_name_label": "Name for the TTS",
        "xtts_name_info": "Use a simple name",
        "xtts_dereverb_label": "Dereverb audio",
        "xtts_dereverb_info": "Dereverb audio: Applies vocal dereverb to the audio",
        "xtts_button": "Process the audio and include it in the TTS selector",
        "xtts_footer": "Generate voice xtts automatically: You can use `_XTTS_/AUTOMATIC.wav` in the TTS selector to automatically generate segments for each speaker when generating the translation.",
        "extra_setting": "Advanced Settings",
        "acc_max_label": "Max Audio acceleration",
        "acc_max_info": "Maximum acceleration for translated audio segments to avoid overlapping. A value of 1.0 represents no acceleration",
        "acc_rate_label": "Acceleration Rate Regulation",
        "acc_rate_info": "Acceleration Rate Regulation: Adjusts acceleration to accommodate segments requiring less speed, maintaining continuity and considering next-start timing.",
        "or_label": "Overlap Reduction",
        "or_info": "Overlap Reduction: Ensures segments don't overlap by adjusting start times based on previous end times; could disrupt synchronization.",
        "aud_mix_label": "Audio Mixing Method",
        "aud_mix_info": "Mix original and translated audio files to create a customized, balanced output with two available mixing modes.",
        "vol_ori": "Volume original audio",
        "vol_tra": "Volume translated audio",
        "voiceless_tk_label": "Voiceless Track",
        "voiceless_tk_info": "Voiceless Track: Remove the original audio voices before combining it with the translated audio.",
        "sub_type": "Subtitle type",
        "soft_subs_label": "Soft Subtitles",
        "soft_subs_info": "Soft Subtitles: Optional subtitles that viewers can turn on or off while watching the video.",
        "burn_subs_label": "Burn Subtitles",
        "burn_subs_info": "Burn Subtitles: Embed subtitles into the video, making them a permanent part of the visual content.",
        "whisper_title": "Config transcription.",
        "lnum_label": "Literalize Numbers",
        "lnum_info": "Literalize Numbers: Replace numerical representations with their written equivalents in the transcript.",
        "scle_label": "Sound Cleanup",
        "scle_info": "Sound Cleanup: Enhance vocals, remove background noise before transcription for utmost timestamp precision. This operation may take time, especially with lengthy audio files.",
        "sd_limit_label": "Segment Duration Limit",
        "sd_limit_info": "Specify the maximum duration (in seconds) for each segment. The audio will be processed using VAD, limiting the duration for each segment chunk.",
        "asr_model_info": "It converts spoken language to text using the 'Whisper model' by default. Use a custom model, for example, by inputting the repository name 'BELLE-2/Belle-whisper-large-v3-zh' in the dropdown to utilize a Chinese language finetuned model. Find finetuned models on Hugging Face.",
        "ctype_label": "Compute type",
        "ctype_info": "Choosing smaller types like int8 or float16 can improve performance by reducing memory usage and increasing computational throughput, but may sacrifice precision compared to larger data types like float32.",
        "batchz_label": "Batch size",
        "batchz_info": "Reducing the batch size saves memory if your GPU has less VRAM and helps manage Out of Memory issues.",
        "tsscale_label": "Text Segmentation Scale",
        "tsscale_info": "Divide text into segments by sentences, words, or characters. Word and character segmentation offer finer granularity, useful for subtitles; disabling translation preserves original structure.",
        "srt_file_label": "Upload an SRT subtitle file (will be used instead of the transcription of Whisper)",
        "divide_text_label": "Redivide text segments by:",
        "divide_text_info": "(Experimental) Enter a separator to split existing text segments in the source language. The tool will identify occurrences and create new segments accordingly. Specify multiple separators using |, e.g.: !|?|...|。",
        "diarization_label": "Diarization model",
        "tr_process_label": "Translation process",
        "out_type_label": "Output type",
        "out_name_label": "File name",
        "out_name_info": "The name of the output file",
        "task_sound_label": "Task Status Sound",
        "task_sound_info": "Task Status Sound: Plays a sound alert indicating task completion or errors during execution.",
        "cache_label": "Retrieve Progress",
        "cache_info": "Retrieve Progress: Continue process from last checkpoint.",
        "preview_info": "Preview cuts the video to only 10 seconds for testing purposes. Please deactivate it to retrieve the full video duration.",
        "edit_sub_label": "Edit generated subtitles",
        "edit_sub_info": "Edit generated subtitles: Allows you to run the translation in 2 steps. First with the 'GET SUBTITLES AND EDIT' button, you get the subtitles to edit them, and then with the 'TRANSLATE' button, you can generate the video",
        "button_subs": "GET SUBTITLES AND EDIT",
        "editor_sub_label": "Generated subtitles",
        "editor_sub_info": "Feel free to edit the text in the generated subtitles here. You can make changes to the interface options before clicking the 'TRANSLATE' button, except for 'Source language', 'Translate audio to', and 'Max speakers', to avoid errors. Once you're finished, click the 'TRANSLATE' button.",
        "editor_sub_ph": "First press 'GET SUBTITLES AND EDIT' to get the subtitles",
        "button_translate": "TRANSLATE",
        "output_result_label": "DOWNLOAD TRANSLATED VIDEO",
        "sub_ori": "Subtitles",
        "sub_tra": "Translated subtitles",
        "ht_token_info": "One important step is to accept the license agreement for using Pyannote. You need to have an account on Hugging Face and accept the license to use the models: https://huggingface.co/pyannote/speaker-diarization and https://huggingface.co/pyannote/segmentation. Get your KEY TOKEN here: https://hf.co/settings/tokens",
        "ht_token_ph": "Token goes here...",
        "tab_docs": "Document translation",
        "docs_input_label": "Choose Document Source",
        "docs_input_info": "It can be PDF, DOCX, TXT, or text",
        "docs_source_info": "This is the original language of the text",
        "chunk_size_label": "Max number of characters that the TTS will process per segment",
        "chunk_size_info": "A value of 0 assigns a dynamic and more compatible value for the TTS.",
        "docs_button": "Start Language Conversion Bridge",
        "cv_url_info": "Automatically download the R.V.C. models from the URL. You can use links from HuggingFace or Drive, and you can include several links, each one separated by a comma. Example: https://huggingface.co/sail-rvc/yoimiya-jp/blob/main/model.pth, https://huggingface.co/sail-rvc/yoimiya-jp/blob/main/model.index",
        "replace_title": "Replace voice: TTS to R.V.C.",
        "sec1_title": "### 1. To enable its use, mark it as enable.",
        "enable_replace": "Check this to enable the use of the models.",
        "sec2_title": "### 2. Select a voice that will be applied to each TTS of each corresponding speaker and apply the configurations.",
        "sec2_subtitle": "Depending on how many <TTS Speaker> you will use, each one needs its respective model. Additionally, there is an auxiliary one if for some reason the speaker is not detected correctly.",
        "cv_tts1": "Choose the voice to apply for Speaker 1.",
        "cv_tts2": "Choose the voice to apply for Speaker 2.",
        "cv_tts3": "Choose the voice to apply for Speaker 3.",
        "cv_tts4": "Choose the voice to apply for Speaker 4.",
        "cv_tts5": "Choose the voice to apply for Speaker 5.",
        "cv_tts6": "Choose the voice to apply for Speaker 6.",
        "cv_tts7": "Choose the voice to apply for Speaker 7.",
        "cv_tts8": "Choose the voice to apply for Speaker 8.",
        "cv_tts9": "Choose the voice to apply for Speaker 9.",
        "cv_tts10": "Choose the voice to apply for Speaker 10.",
        "cv_tts11": "Choose the voice to apply for Speaker 11.",
        "cv_tts12": "Choose the voice to apply for Speaker 12.",
        "cv_aux": "- Voice to apply in case a Speaker is not detected successfully.",
        "cv_button_apply": "APPLY CONFIGURATION",
        "tab_help": ":P",
    },
}
